"""Which curated demo beats the app is allowed to surface as one-click buttons.

WHY this guard exists: demo_genomes.json is a gitignored DATA artifact (regenerated by
scripts/pick_demo_genomes.py on every retrain). `git checkout -- .` cannot revert it, so when a
beat's *rendering code* is reverted, its stale entry can linger in the data file and re-promote a
removed demo as a curated button on stage. Cycle 41 reverted a "dark-AMR" beat — a lineage FALSE
POSITIVE where the firewall committed ceftriaxone RESISTANT at 91% on a genome whose shipped lab
phenotype is ceftriaxone-treatable — but the entry survived in demo_genomes.json and stayed live.
So the reader ALLOWLISTS the beats it actually renders and drops anything else, regardless of how
the data file got stale. Fails safe: a genuinely new beat added to pick_demo but not here is simply
not surfaced (visibly absent), never a stale one silently shown.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterable

# The beats scripts/pick_demo_genomes.py canonically writes AND demo/app.py knows how to render.
# "qrdr" is a known-gene beat rendered by the same generic report path (the app is beat-type-blind);
# it earns its own name so pick_demo/preflight can gate it on the QRDR-specific contract (a
# lab-Resistant fluoroquinolone whose knockout Δ corroborates the gyrA mutation).
SUPPORTED_BEATS = frozenset({"known_gene", "ood", "qrdr"})


def supported_presets(entries: Iterable[dict[str, str]]) -> list[dict[str, str]]:
    """Keep only presets whose beat the current code renders — drop stale/reverted beats."""
    return [e for e in entries if e.get("beat") in SUPPORTED_BEATS]
